import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

import shutil
from fastapi import FastAPI, UploadFile, File, HTTPException
from pydantic import BaseModel
from rag_service import RAGService

app = FastAPI(title="DocuBrain API")

# Initialize the RAG service
print("--- System Startup: Initializing RAG Service ---")
rag = RAGService()
print("--- System Startup: RAG Service Initialized ---")

# Request model for chat (must match frontend payload)
class QueryRequest(BaseModel):
    query: str

@app.post("/ingest")
async def ingest_document(file: UploadFile = File(...)):
    # 1. Save uploaded file temporarily
    temp_file = f"temp_{file.filename}"
    
    # [Debug Log] Print the filename being received
    print(f"\n[DEBUG-INGEST] Received upload request, filename: {file.filename}")

    with open(temp_file, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
    
    try:
        # 2. Process and index the file
        print(f"[DEBUG-INGEST] Calling rag.ingest_file to process file...")
        
        # Call your RAG service
        result = rag.ingest_file(temp_file)
        
        # [Key Debug Log] Check the result of the ingestion. 
        # If this returns "Success" but retrieval fails later, it might be a PDF parsing issue.
        print(f"[DEBUG-INGEST] rag.ingest_file result: {result}")
        
        return result
    except Exception as e:
        # Print detailed error to console
        print(f"[ERROR-INGEST] Error occurred: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        # 3. Cleanup temp file
        if os.path.exists(temp_file):
            os.remove(temp_file)
            print(f"[DEBUG-INGEST] Temp file cleaned up: {temp_file}")

@app.post("/ask")
async def ask_question(request: QueryRequest):
    # [Debug Log] Print the user's question
    print(f"\n[DEBUG-ASK] Received user question: {request.query}")
    
    try:
        # Generate answer using RAG
        answer = rag.ask_question(request.query)
        
        # [Debug Log] Print the raw answer generated by AI
        print(f"[DEBUG-ASK] RAG returned answer: {answer}")
        
        return answer
    except Exception as e:
        print(f"[ERROR-ASK] Question processing failed: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))